## Spam Filter Model - 21BAI1007
Sir, Another code file is provided along the submission which has a User Interface

### 1. Importing Necessary Libraries and Modules

In [30]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

from sklearn import preprocessing 
from sklearn.preprocessing import RobustScaler
from sklearn.metrics import mean_squared_error

### 2. Importing and loading the dataset

In [31]:
df = pd.read_csv("spam.csv", encoding='latin1')
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

### 3. Data Preprocessing

In [32]:
# Removing the unwanted columns generated as a result of encoding
df.drop(columns=['Unnamed: 2', 'Unnamed: 3', "Unnamed: 4"], inplace=True)

In [33]:
# Renaming the column 'v1' to 'category' and 'v2' to 'message'
df.rename(columns = {'v1':'Category'}, inplace = True)
df.rename(columns = {'v2':'Message'}, inplace = True)
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [34]:
# Inspecting the data
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    653  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [35]:
# Encoding 'category' according to spam or not spam.
# 1 if spam, 0 if not
df['spam'] = df['Category'].apply(lambda x:1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [36]:
# Splitting the data into train and test
x = df.Message
y = df.spam
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

In [37]:
x_train.describe(), x_test.describe()

(count                       4179
 unique                      3936
 top       Sorry, I'll call later
 freq                          26
 Name: Message, dtype: object,
 count                       1393
 unique                      1357
 top       Sorry, I'll call later
 freq                           4
 Name: Message, dtype: object)

In [38]:
y_train.describe(), y_test.describe()

(count    4179.000000
 mean        0.133046
 std         0.339665
 min         0.000000
 25%         0.000000
 50%         0.000000
 75%         0.000000
 max         1.000000
 Name: spam, dtype: float64,
 count    1393.000000
 mean        0.137114
 std         0.344091
 min         0.000000
 25%         0.000000
 50%         0.000000
 75%         0.000000
 max         1.000000
 Name: spam, dtype: float64)

In [39]:
# Counting the frequecy of each word using the count vectorizer
# Finding the word count and storing the data as a numerical matrix
count = CountVectorizer()
x_train_count = count.fit_transform(x_train.values)
x_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

### 3. Training the model

In [40]:
# Declaring and fitting our data to the naive bayes model
lassifier = MultinomialNB()
classifier.fit(x_train_count, y_train)

MultinomialNB()

In [41]:
# Pretest
email_ham = ["You won 1000$. Click the link below"]
email_ham_count = count.transform(email_ham)
classifier.predict(email_ham_count)

array([1])

### 4. Testing the model

In [43]:
# Count vectorizing the test dataset
x_test_count = count.transform(x_test)
# Testing the accuracy
classifier.score(x_test_count, y_test)*100

98.34888729361091

### 5. User Inputs and Final Output

In [48]:
# 1 - Message is spam
# 2 - Message os genuine

user_message = input()
inp = [user_message]
message_count = count.transform(inp)
classifier.predict(message_count)

your bank has been credited with Rs 25000. click the link to claim it.


array([1])